### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-couchdb2#60]
## Description
Currently there is one failed test case in CI.

```
16:31:57   1) CouchDB2 imported features
16:31:57        include
16:31:57          should report errors if the PK is excluded:
16:31:57      Uncaught AssertionError: expected null to exist
16:31:57       at node_modules/loopback-datasource-juggler/test/include.test.js:81:14
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1707:9
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1140:9
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
16:31:57       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1137:13
16:31:57       at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:1673:11)
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1687:13
16:31:57       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
16:31:57       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
16:31:57       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
16:31:57       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
16:31:57       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
16:31:57       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
16:31:57       at withNotify (node_modules/loopback-datasource-juggler/lib/dao.js:1685:17)
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1626:11
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1135:9
16:31:57       at eachOfArrayLike (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1069:9)
16:31:57       at eachOf (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1117:5)
16:31:57       at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1133:5)
16:31:57       at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1122:16)
16:31:57       at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1621:13)
16:31:57       at lib/couchdb.js:315:5
16:31:57       at CouchDB._extendDocs (lib/couchdb.js:1105:58)
16:31:57       at lib/couchdb.js:1091:12
16:31:57       at node_modules/loopback-datasource-juggler/lib/include.js:194:11
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
16:31:57       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
16:31:57       at targetFetchHandler (node_modules/loopback-datasource-juggler/lib/include.js:635:9)
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1707:9
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1140:9
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:473:16
16:31:57       at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1064:13)
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:969:16
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1137:13
16:31:57       at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:1673:11)
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1687:13
16:31:57       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
16:31:57       at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
16:31:57       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
16:31:57       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
16:31:57       at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
16:31:57       at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
16:31:57       at withNotify (node_modules/loopback-datasource-juggler/lib/dao.js:1685:17)
16:31:57       at node_modules/loopback-datasource-juggler/lib/dao.js:1626:11
16:31:57       at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1135:9
16:31:57       at eachOfArrayLike (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1069:9)
16:31:57       at eachOf (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1117:5)
16:31:57       at _asyncMap (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1133:5)
16:31:57       at Object.map (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1122:16)
16:31:57       at allCb (node_modules/loopback-datasource-juggler/lib/dao.js:1621:13)
16:31:57       at lib/couchdb.js:315:5
16:31:57       at CouchDB._extendDocs (lib/couchdb.js:1105:58)
16:31:57       at lib/couchdb.js:1091:12
16:31:57       at include (lib/couchdb.js:310:7)
16:31:57       at lib/couchdb.js:1090:5
16:31:57       at Request._callback (node_modules/nano/lib/nano.js:221:16)
16:31:57       at Request.self.callback (node_modules/request/request.js:185:22)
16:31:57       at Request.<anonymous> (node_modules/request/request.js:1161:10)
16:31:57       at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
16:31:57       at endReadableNT (_stream_readable.js:1064:12)
16:31:57       at _combinedTickCallback (internal/process/next_tick.js:139:11)
16:31:57       at process._tickCallback (internal/process/next_tick.js:181:9)
16:31:57 
16:31:57 
```

Related to PR #59

**Comment by dhmlau** [comment]
Also see https://github.com/strongloop/loopback-datasource-juggler/pull/1705#issuecomment-480254509

**Comment by jannyHou** [comment]
closed as https://github.com/strongloop/loopback-datasource-juggler/pull/1720 and https://github.com/strongloop/loopback-connector-couchdb2/pull/59 get merged.
